.class public final Lcom/google/android/gms/internal/cg;
.super Lcom/google/android/gms/common/api/v;


# instance fields
.field final mStatus:Lcom/google/android/gms/common/api/Status;


# virtual methods
.method public final a(Lcom/google/android/gms/common/api/z;)V
    .locals 1

    new-instance p1, Ljava/lang/UnsupportedOperationException;

    const-string v0, "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()"

    invoke-direct {p1, v0}, Ljava/lang/UnsupportedOperationException;-><init>(Ljava/lang/String;)V

    throw p1
.end method
